---
swagger: "2.0"
info:
  x-ibm-name: "addcustomermessage"
  title: "addcustomermessage"
  version: "1.0.0"
schemes:
- "https"
host: "$(catalog.host)"
basePath: "/addcustomermessage"
consumes:
- "application/json"
produces:
- "application/json"
securityDefinitions: {}
x-ibm-configuration:
  testable: true
  enforced: true
  cors:
    enabled: true
  assembly:
    execute:
    - gatewayscript:
        title: "gatewayscript"
        version: "1.0.0"
        source: "session.output.write({\r\n  \"success\":\"Success\"\r\n});\r\napim.output(\"\
          application/json\");"
  phase: "realized"
paths:
  /addcustomermessage:
    post:
      responses:
        200:
          description: "200 OK"
        400:
          description: "Bad Response"
      parameters:
      - name: "body"
        required: true
        in: "body"
        schema:
          type: "object"
definitions: {}
tags: []
