---
swagger: "2.0"
info:
  x-ibm-name: "dummy-retail-api-common"
  title: "dummy retail API common"
  version: "1.0.0"
schemes:
- "https"
host: "$(catalog.host)"
basePath: "/dummy-retail-api-common"
consumes:
- "application/json"
produces:
- "application/json"
securityDefinitions: {}
x-ibm-configuration:
  testable: true
  enforced: true
  cors:
    enabled: true
  assembly:
    execute:
    - invoke:
        target-url: "$(target-url)$(request.path)"
  phase: "realized"
paths: {}
definitions: {}
tags: []
